Display offline group memebers in grey
crusttech/webapp-messaging pull request #44
Opened 2019-05-28 19:09 UTC by Fajfa

ref: #42 

Displays online users first, final result: 
![Screenshot from 2019-05-28 21-08-26](https://user-images.githubusercontent.com/15791641/58505233-c8749980-818c-11e9-8535-2dd8ae508a53.png)

2019-05-28 19:23 UTC, zmija commented on src/assets/sass/_0.commons.scss
> +  &.member-offline {
can you please move this to the component instead of external scss file?

2019-05-28 19:35 UTC, darh requested changes

2019-05-28 19:35 UTC, darh commented on src/components/Channel/Header.vue
> +      <span class="channel-name" :class="[channel.type]" v-html="label(channel, true)">
this looks like an error to me?
old version inserted label into span without messing with the existig content. 

You are doing v-html that will replace all existing content of that tag:

https://jsfiddle.net/Laq8b60n/1/

2019-05-28 19:35 UTC, darh commented on src/mixins/labels.js
> +        let groupMembers = this.$store.getters['channels/otherMembersOf'](c.channelID, this.$auth.user.userID)
Let's extract all this logic into new component - `<group-members>` that will have that single responsibility -- display members of a group. Be smart with props.

2019-05-28 19:35 UTC, darh commented on src/mixins/labels.js
> +              return `<span class="member-offline">${label}</span>`
Let's not solve this problem with a hammer :)
While extracting this into a new component, move this into component's template.

2019-05-28 19:35 UTC, darh commented on src/mixins/labels.js
> +            if (a.includes('span')) {
Please don't.

2019-05-29 16:21 UTC, darh requested changes
Much better and much more readable!

But let's improve this a little bit more:
The component's name is `GroupMembers`, for me, that means that it knows how to output group members. Current code does more than that -- it checks if passed Channel is a group and this affects the output. 

There are at least 2 way how to improve this - let me know which one you've picked and why ;)

2019-05-29 17:53 UTC, merged