Optimize user and message fetching
crusttech/webapp-messaging pull request #79
Opened 2019-11-04 14:42 UTC by Fajfa

The initial number of messages loaded changed from 100 to 20
Number of messages loaded when scrolling up changed from 100 to 50

We no longer fetch all of the users. Instead:
- Users from group channels are fetched on initial load
- Users from a specific channel are fetched on channel first load
- Adding members uses the query option on userList, when a member is added it's added to the store
- The users in the search are fetched based on the search results. We go through result messages and fetch the users that are not yet in the store
- User links are also fetched on demand. If user is not yet in store. 

The only known case where the ID of a user wont translate to a name is if the user was removed from a group. There are a couple of possible solutions, still choosing one. 

**Performance without optimization:**
Around 11 seconds
![Screenshot from 2019-11-04 15-13-13](https://user-images.githubusercontent.com/15791641/68128789-ad1a7100-ff18-11e9-9f83-ff3ac24c07ca.png)

**Performance with optimization**
Around 8 seconds
![Screenshot from 2019-11-04 15-31-20](https://user-images.githubusercontent.com/15791641/68128821-bdcae700-ff18-11e9-96df-ba7dd66ad66c.png)

2019-11-04 14:44 UTC, tjerman commented
I see a possible problem -- what if I have a tall screen and I can show more than 20 messages. Is this covered? I think the number of messages should be determined dynamically -- `innerHeight / msgMinHeight`

2019-11-04 16:07 UTC, darh commented
Before going in with some big math, please benchmark how much diff does it make now (including all other speedups) with different num. of messages loaded...

2019-11-05 09:14 UTC, tjerman requested changes
This will also require changes for the good'ol mentions -- It currently preps a set of available suggestions based on the current state and doesn't do any API interactions.

2019-11-05 09:14 UTC, tjerman commented on src/components/Panel/Rightside/Members.vue
> +          })
Even tho, this is safe by the `.forEach` documentation, this feels wrong to me and there is probably a browser version, that will not work as intended.

Just use `(set || [])`, or eaven better:
```js
        this.$SystemAPI.userList(({ query, limit })).then(({ set = [] }) => {
          set.forEach(u => {
```

2019-11-05 10:26 UTC, Fajfa commented
> This will also require changes for the good'ol mentions -- It currently preps a set of available suggestions based on the current state and doesn't do any API interactions.

The mentions work fine if we only include channel members in the available mentions.
When the quill -> tiptap migration happens we can also include all of the other user in the mentions.
I would much rather wait for the migration to happen first.

2019-11-08 15:21 UTC, Fajfa commented
Mentions updated.
Ready to merge in my opinion.

2019-11-08 15:24 UTC, tjerman commented
I'll take a look a bit later :+1:

2019-11-08 19:38 UTC, tjerman requested changes
Add tests.

2019-11-08 19:38 UTC, tjerman commented on src/components/Messages/Message/index.vue
> +import { mapGetters, mapActions } from 'vuex'
No. I told you that these components should be as simple as possible. The same goes for below's `created ()` hook.

2019-11-08 19:38 UTC, tjerman commented on src/components/Messages/Message/index.vue
> +
This can easily be handled when messages are fetched from API

2019-11-08 19:38 UTC, tjerman commented on src/components/Messages/index.vue
> +      type: [Object, String],
I don't know if this is a good idea. If you ask me I'd prefer to see an identifier in a String format instead of a mix-and-match.

2019-11-08 19:38 UTC, tjerman commented on src/components/Messages/index.vue
> +      }
`Messages.vue` component is not responsible for this. It should know how to list & show messages, not worry about things such as user existence.

You can define a mixin to handle this for Channel, Thread, ...

2019-11-08 19:38 UTC, tjerman commented on src/components/Panel/Channels/index.vue
> +      if (newChannels.length > oldChannels.length) {
I am 99% sure that this won't work due to references -- new and old will be the same. Please doublecheck & test!

Also -- this length difference check might not be good enough. Can cases where a channel is replaced by another channel happen?

2019-11-08 19:38 UTC, tjerman commented on src/components/Panel/Channels/index.vue
> +        if (memberIDs.size > 0) {
This check can be a responsibility of `fetchUsers` (it already is, so this is not needed)

2019-11-08 19:38 UTC, tjerman commented on src/components/Panel/Rightside/Members.vue
> +        const limit = 15
A bit overkill -- `userList(({ query, limit }))` already defines that 15 is limit, so no need to worry about magic-numbers

2019-11-08 19:38 UTC, tjerman commented on src/components/Panel/Rightside/Members.vue
> +      }
We should probably debounce or throttle this; don't want to make API sweet too much

2019-11-08 19:38 UTC, tjerman commented on src/mixins/core.js
> +// Disabling this for now because of user fetching rework
Just delete these if they won't be useful anymore

2019-11-08 19:38 UTC, tjerman commented on src/views/ChannelEditor.vue
> +    },
Same here.. Debounce/throttle it

2019-11-08 19:38 UTC, tjerman commented on src/views/Messenger.vue
> +        // this.loadUsers()
Remove

2019-11-08 19:38 UTC, tjerman commented on src/components/MessageInput/TextInput.vue
> +            source: async function (searchTerm, renderList, mentionChar) {
(keep in mind) -- This will need to be refactored when TipTap migration gets merged.

2019-11-08 19:38 UTC, tjerman commented on src/components/MessageInput/TextInput.vue
> +            source: async function (searchTerm, renderList, mentionChar) {
But still, add a test or two, to make sure it works

2019-12-02 11:16 UTC, merged